<?php

declare(strict_types=1);
$catalogo = [
    [
        'id' => 1,
        'titulo' => 'Dune',
        'autor' => 'Frank Herbert',
        'genero' => 'ciencia ficcion',
        'paginas' => 412,
        'disponible' => true,
        'fechaAlta' => '2026-09-01',
    ],
    [
        'id' => 2,
        'titulo' => 'El nombre del viento',
        'autor' => 'Patrick Rothfuss',
        'genero' => 'fantasia',
        'paginas' => 872,
        'disponible' => false,
        'fechaAlta' => '2026-08-18',
    ],
    [
        'id' => 3,
        'titulo' => 'Un mago de Terramar',
        'autor' => 'Ursula K. Le Guin',
        'genero' => 'fantasia',
        'paginas' => 256,
        'disponible' => true,
        'fechaAlta' => '2026-07-03',
    ],
    [
        'id' => 4,
        'titulo' => '1984',
        'autor' => 'George Orwell',
        'genero' => 'distopia',
        'paginas' => 352,
        'disponible' => true,
        'fechaAlta' => '2026-06-20',
    ],
    [
        'id' => 5,
        'titulo' => 'Solaris',
        'autor' => 'Stanislaw Lem',
        'genero' => 'ciencia ficcion',
        'paginas' => 288,
        'disponible' => false,
        'fechaAlta' => '2026-05-12',
    ],
    [
        'id' => 6,
        'titulo' => 'Frankenstein',
        'autor' => 'Mary Shelley',
        'genero' => 'terror',
        'paginas' => 304,
        'disponible' => true,
        'fechaAlta' => '2026-04-22',
    ],
    [
        'id' => 7,
        'titulo' => 'Dracula',
        'autor' => 'Bram Stoker',
        'genero' => 'terror',
        'paginas' => 480,
        'disponible' => false,
        'fechaAlta' => '2026-03-14',
    ],
    [
        'id' => 8,
        'titulo' => 'El hobbit',
        'autor' => 'J. R. R. Tolkien',
        'genero' => 'fantasia',
        'paginas' => 310,
        'disponible' => true,
        'fechaAlta' => '2026-02-10',
    ],
    [
        'id' => 9,
        'titulo' => 'Fundacion',
        'autor' => 'Isaac Asimov',
        'genero' => 'ciencia ficcion',
        'paginas' => 320,
        'disponible' => true,
        'fechaAlta' => '2026-01-16',
    ],
    [
        'id' => 10,
        'titulo' => 'La llamada de Cthulhu',
        'autor' => 'H. P. Lovecraft',
        'genero' => 'terror',
        'paginas' => 176,
        'disponible' => true,
        'fechaAlta' => '2025-12-05',
    ],
    [
        'id' => 11,
        'titulo' => 'Fahrenheit 451',
        'autor' => 'Ray Bradbury',
        'genero' => 'distopia',
        'paginas' => 272,
        'disponible' => false,
        'fechaAlta' => '2025-11-11',
    ],
    [
        'id' => 12,
        'titulo' => 'El camino de los reyes',
        'autor' => 'Brandon Sanderson',
        'genero' => 'fantasia',
        'paginas' => 1200,
        'disponible' => true,
        'fechaAlta' => '2025-10-01',
    ],
];