<?php
$libros = [
    [
        'id' => 1,
        'titulo' => 'El Principito',
        'autor' => 'Antoine de Saint-Exupéry',
        'genero' => 'Ficción',
        'paginas' => 96,
        'disponible' => true,
        'fechaAlta' => '2023-01-15',
    ],
    [
        'id' => 2,
        'titulo' => 'Cien Años de Soledad',
        'autor' => 'Gabriel García Márquez',
        'genero' => 'fantasia',
        'paginas' => 417,
        'disponible' => false,
        'fechaAlta' => '2023-02-10',
    ],
    [
        'id' => 3,
        'titulo' => '1984',
        'autor' => 'George Orwell',
        'genero' => 'Distopia',
        'paginas' => 328,
        'disponible' => true,
        'fechaAlta' => '2023-03-05',
    ],
    [
        'id' => 4,
        'titulo' => 'Don Quijote de la Mancha',
        'autor' => 'Miguel de Cervantes',
        'genero' => 'Novela',
        'paginas' => 863,
        'disponible' => true,
        'fechaAlta' => '2023-04-20',
    ],
    [
        'id' => 5,
        'titulo' => 'La Sombra del Viento',
        'autor' => 'Carlos Ruiz Zafón',
        'genero' => 'Misterio',
        'paginas' => 487,
        'disponible' => false,
        'fechaAlta' => '2023-05-12',
    ],
    [
        'id' => 6,
        'titulo' => 'El Hobbit',
        'autor' => 'J.R.R. Tolkien',
        'genero' => 'Fantasia',
        'paginas' => 310,
        'disponible' => true,
        'fechaAlta' => '2023-06-18',
    ],
    [
        'id' => 7,
        'titulo' => 'Matar a un Ruiseñor',
        'autor' => 'Harper Lee',
        'genero' => 'fantasia',
        'paginas' => 281,
        'disponible' => false,
        'fechaAlta' => '2023-07-22',
    ],
    [
        'id' => 8,
        'titulo' => 'El Código Da Vinci',
        'autor' => 'Dan Brown',
        'genero' => 'fantasia',
        'paginas' => 489,
        'disponible' => false,
        'fechaAlta' => '2023-08-30',
    ]
];