<?php

declare(strict_types=1);

$videojuegos = [
    [
        'id' => 1,
        'titulo' => 'Arena Vector',
        'estudio' => 'Axis Byte',
        'genero' => 'accion',
        'plataforma' => 'pc',
        'precio' => 9.99,
        'puntuacion' => 6.4,
        'disponible' => true,
        'fechaLanzamiento' => '2024-03-08',
    ],
    [
        'id' => 2,
        'titulo' => 'Reinos de Cristal',
        'estudio' => 'North Crown',
        'genero' => 'rol',
        'plataforma' => 'pc',
        'precio' => 59.99,
        'puntuacion' => 9.8,
        'disponible' => true,
        'fechaLanzamiento' => '2025-11-14',
    ],
    [
        'id' => 3,
        'titulo' => 'Sombras de Neón',
        'estudio' => 'Neon Forge',
        'genero' => 'accion',
        'plataforma' => 'ps5',
        'precio' => 79.99,
        'puntuacion' => 9.0,
        'disponible' => true,
        'fechaLanzamiento' => '2026-08-21',
    ],
    [
        'id' => 4,
        'titulo' => 'Circuito Cero',
        'estudio' => 'Redline Works',
        'genero' => 'carreras',
        'plataforma' => 'xsx',
        'precio' => 44.99,
        'puntuacion' => 7.6,
        'disponible' => false,
        'fechaLanzamiento' => '2025-06-06',
    ],
    [
        'id' => 5,
        'titulo' => 'Tácticas Orbitales',
        'estudio' => 'Kepler Studio',
        'genero' => 'estrategia',
        'plataforma' => 'pc',
        'precio' => 34.50,
        'puntuacion' => 8.5,
        'disponible' => true,
        'fechaLanzamiento' => '2026-02-13',
    ],
    [
        'id' => 6,
        'titulo' => 'Valle de Ceniza',
        'estudio' => 'Ember Fox',
        'genero' => 'rol',
        'plataforma' => 'sw',
        'precio' => 49.95,
        'puntuacion' => 8.8,
        'disponible' => true,
        'fechaLanzamiento' => '2024-10-25',
    ],
    [
        'id' => 7,
        'titulo' => 'Mareas de Acero',
        'estudio' => 'Breakwater Games',
        'genero' => 'aventura',
        'plataforma' => 'ps5',
        'precio' => 54.90,
        'puntuacion' => 8.1,
        'disponible' => false,
        'fechaLanzamiento' => '2025-09-19',
    ],
    [
        'id' => 8,
        'titulo' => 'Pixel Frontier',
        'estudio' => 'Tiny Horizon',
        'genero' => 'simulacion',
        'plataforma' => 'pc',
        'precio' => 24.99,
        'puntuacion' => 7.9,
        'disponible' => true,
        'fechaLanzamiento' => '2026-01-30',
    ],
    [
        'id' => 9,
        'titulo' => 'Nexo Salvaje',
        'estudio' => 'Wild Node',
        'genero' => 'accion',
        'plataforma' => 'xsx',
        'precio' => 64.99,
        'puntuacion' => 8.9,
        'disponible' => true,
        'fechaLanzamiento' => '2025-12-05',
    ],
    [
        'id' => 10,
        'titulo' => 'Eco de las Ruinas',
        'estudio' => 'Quiet Room',
        'genero' => 'terror',
        'plataforma' => 'ps5',
        'precio' => 39.99,
        'puntuacion' => 7.3,
        'disponible' => true,
        'fechaLanzamiento' => '2026-04-17',
    ],
    [
        'id' => 11,
        'titulo' => 'Crónicas del Alba',
        'estudio' => 'Aurora Tale',
        'genero' => 'rol',
        'plataforma' => 'sw',
        'precio' => 29.99,
        'puntuacion' => 8.3,
        'disponible' => false,
        'fechaLanzamiento' => '2025-02-28',
    ],
    [
        'id' => 12,
        'titulo' => 'Leyendas del Umbral',
        'estudio' => 'Threshold Lab',
        'genero' => 'aventura',
        'plataforma' => 'xsx',
        'precio' => 69.90,
        'puntuacion' => 9.2,
        'disponible' => true,
        'fechaLanzamiento' => '2026-09-15',
    ],
];

$plataformas = [
    'xsx' => 'Xbox Series X|S',
    'sw' => 'Nintendo Switch',
    'pc' => 'PC',
    'ps5' => 'PlayStation 5',
];

$ventasSemana = [
    'pc' => 128,
    'ps5' => 96,
    'sw' => 72,
    'xsx' => 104,
];
